.only-default: &only-default
  only:
    - api
    - web
    - main

stages:
  - install
  - build
  - security-check
  - deploy

install:
  <<: *only-default
  stage: install
  image: node:14.0.0
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
  script:
    - echo "Install project dependecies"
    - node -v
    - npm -v
    - npm ci
    - echo "Install successful"

build:
  <<: *only-default
  stage: build
  image: node:14.0.0
  script:
    - echo "Build started"
    - node -v
    - npm -v
    - npm run build
    - echo "Build successfull"
  artifacts:
    paths:
      - build/

scan:
  stage: security-check
  image:
    name: owasp/zap2docker-stable
# will uncomment the following lines before merging the MR
#  only:
#    - origin master
  script: 
    - zap-baseline.py -t https://vc-generator.com/

deploy:
  <<: *only-default
  stage: deploy
  dependencies:
    - build
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  script:
    - aws s3 cp build/ s3://$S3_BUCKET/ --recursive
