export const AccountCredentialPersonV1 =  {
        type: 'AccountCredentialPersonV1',
        data: {
          '@type': ['Person', 'PersonE', 'AccountPerson'],
          hasAccount: {
            '@type': 'Account',
            identifier: '1234',
            organization: {
              '@type': ['Organization', 'OrganizationE', 'OrganizationAccount'],
              serviceTypes: ['type1', 'type2'],
              nationality: {
                '@type': 'State',
                name: 'Washington',
              },
              name: 'My Org',
            },
            startDate: '2020-06-01T00:00:00.000Z',
            endDate: '2021-06-01T00:00:00.000Z',
            accountType: 'accountType',
            accountTypeConfidence: 1,
            accountStatements: [
              {
                '@type': 'AccountStatement',
                statementDate: '2020-06-01T00:00:00.000Z',
                dueDate: '2020-07-01T00:00:00.000Z',
              },
            ],
            accountPayments: [
              {
                '@type': 'AccountPayment',
                paymentDate: '2020-06-01T00:00:00.000Z',
                amount: {
                  '@type': 'MonetaryAmount',
                  value: '1000',
                  currency: 'USD',
                  maxValue: '100',
                },
              },
            ],
            hasValue: {
              '@type': 'MonetaryAmount',
              value: '1000',
              currency: 'USD',
              maxValue: '100',
            },
            bankAccountCategory: 'checking',
            hasIncome: {
              '@type': 'BankAccountTransactionGroup',
              identifier: 1234,
              startDate: '2020-06-01T00:00:00.000Z',
              endDate: '2021-06-01T00:00:00.000Z',
              cashflowCategory: 'category',
              cashflowSubcategory: 'subcategory',
              payrollAgency: true,
              memo: 'memo',
              length: 10,
              payee: 'payee',
              payer: 'payer',
              rank: 'rank',
              frequency: 'daily',
              periodicity: 1,
              valueStddev: {
                '@type': 'MonetaryAmount',
                value: '100',
                currency: 'USD',
                maxValue: '100',
              },
              valueTotal: {
                '@type': 'MonetaryAmount',
                value: '100',
                currency: 'USD',
                maxValue: '100',
              },
              valueMean: {
                '@type': 'MonetaryAmount',
                value: '100',
                currency: 'USD',
                maxValue: '100',
              },
              valueMedian: {
                '@type': 'MonetaryAmount',
                value: '100',
                currency: 'USD',
                maxValue: '100',
              },
              transactions: {
                '@type': 'BankAccountTransaction',
                transactionType: 'credit',
                value: {
                  '@type': 'MonetaryAmount',
                  value: '100',
                  currency: 'USD',
                  maxValue: '100',
                },
                memo: 'memo',
              },
            },
            hasExpense: {
              '@type': 'BankAccountTransactionGroup',
              identifier: 1234,
              startDate: '2020-06-01T00:00:00.000Z',
              endDate: '2021-06-01T00:00:00.000Z',
              cashflowCategory: 'category',
              cashflowSubcategory: 'subcategory',
              payrollAgency: true,
              memo: 'memo',
              length: 10,
              payee: 'payee',
              payer: 'payer',
              rank: 'rank',
              frequency: 'daily',
              periodicity: 1,
              valueStddev: {
                '@type': 'MonetaryAmount',
                value: '100',
                currency: 'USD',
                maxValue: '100',
              },
              valueTotal: {
                '@type': 'MonetaryAmount',
                value: '100',
                currency: 'USD',
                maxValue: '100',
              },
              valueMean: {
                '@type': 'MonetaryAmount',
                value: '100',
                currency: 'USD',
                maxValue: '100',
              },
              valueMedian: {
                '@type': 'MonetaryAmount',
                value: '100',
                currency: 'USD',
                maxValue: '100',
              },
              transactions: {
                '@type': 'BankAccountTransaction',
                transactionType: 'credit',
                value: {
                  '@type': 'MonetaryAmount',
                  value: '100',
                  currency: 'USD',
                  maxValue: '100',
                },
                memo: 'memo',
              },
            },
            hasTransactions: [
              {
                '@type': 'BankAccountTransaction',
                transactionType: 'credit',
                value: {
                  '@type': 'MonetaryAmount',
                  value: '100',
                  currency: 'USD',
                  maxValue: '100',
                },
                memo: 'memo',
              },
              {
                '@type': 'BankAccountTransaction',
                transactionType: 'credit',
                value: {
                  '@type': 'MonetaryAmount',
                  value: '100',
                  currency: 'USD',
                  maxValue: '100',
                },
                memo: 'memo',
              },
            ],
          },
          name: 'Bob Belcher',
        },
      }