export const CreditScoreCredentialPersonV1 = {
    type: 'CreditScoreCredentialPersonV1',
    data: {
      '@type': ['Person', 'PersonE', 'CreditScorePerson'],
      name: 'Bob Belcher',
      hasCreditScore: {
        '@type': 'CreditScore',
        score: 0,
        scoreType: 'scoreType',
        populationRank: 0,
        provider: 'provider',
        lastUpdatedDate: 'lastUpdatedDate',
        utilizationPercentage: 0,
        historyStartDate: 'historyStartDate',
        paymentHistoryPercentage: 0,
        statement: 'statement',
        tradelines: [
          {
            '@type': 'Tradeline',
            accountType: 'accountType',
            accountNumber: 'accountNumber',
            creditType: 'creditType',
            balanceCurrent: { '@type': 'MonetaryAmount', value: 100, currency: 'USD' },
            balanceMax: { '@type': 'MonetaryAmount', value: 100, currency: 'USD' },
            balancePercentage: 0,
            rating: 'rating',
            open: true,
            statement: 'statement',

            subscriberCode: 'subscriberCode',
            verifiedDate: 'verifiedDate',
            reportedDate: 'reportedDate',
            openedDate: 'openedDate',
            accountStatusDate: 'accountStatusDate',
            closedDate: 'closedDate',
            bureau: 'bureau',
            accountCondition: 'accountCondition',
            accountDesignator: 'accountDesignator',
            disputeFlag: 'disputeFlag',
            industryCode: 'industryCode',
            accountIsOpen: true,
            payStatus: 'payStatus',
            verificationIndicator: 'verificationIndicator',
            remark: [
              {
                '@type': 'TradelineRemark',
                remark: 'remark',
                remarkCode: 'remarkCode',
              },
            ],
            monthsReviewed: 'monthsReviewed',
            monthlyPayment: 'monthlyPayment',
            late90Count: 'late90Count',
            late60Count: 'late60Count',
            late30Count: 'late30Count',
            dateLatePayment: 'dateLatePayment',
            termMonths: 'termMonths',
            collateral: 'collateral',
            amountPastDue: { '@type': 'MonetaryAmount', value: 100, currency: 'USD' },
            worstPastStatusCount: 'worstPastStatusCount',
            paymentFrequency: 'paymentFrequency',
            termType: 'termType',
            worstPayStatus: 'worstPayStatus',
            payStatuses: [
              {
                '@type': 'TradelinePayStatus',
                date: 'date',
                status: 'status',
              },
            ],
            creditLimit: 'creditLimit',
            creditor: 'creditor',
            position: 'position',
          },
        ],
        creditDataSuppressed: 'creditDataSuppressed',
        totalAccounts: 'totalAccounts',
        totalClosedAccounts: 'totalClosedAccounts',
        delinquentAccounts: 'delinquentAccounts',
        derogatoryAccounts: 'derogatoryAccounts',
        openAccounts: 'openAccounts',
        totalBalances: 'totalBalances',
        totalMonthlyPayments: 'totalMonthlyPayments',
        numberOfInquiries: 'numberOfInquiries',
        totalPublicRecords: 'totalPublicRecords',
        recentInquiries: 'recentInquiries',
        balanceOpenRevolvingAccounts: 'balanceOpenRevolvingAccounts',
        totalOpenRevolvingAccounts: 'totalOpenRevolvingAccounts',
        balanceOpenInstallmentAccounts: 'balanceOpenInstallmentAccounts',
        totalOpenInstallmentAccounts: 'totalOpenInstallmentAccounts',
        balanceOpenMortgageAccounts: 'balanceOpenMortgageAccounts',
        totalOpenMortgageAccounts: 'totalOpenMortgageAccounts',
        balanceOpenCollectionAccounts: 'balanceOpenCollectionAccounts',
        totalOpenCollectionAccounts: 'totalOpenCollectionAccounts',
        balanceOpenOtherAccounts: 'balanceOpenOtherAccounts',
        totalOpenOtherAccounts: 'totalOpenOtherAccounts',
        availableCredit: 'availableCredit',
        utilization: 'utilization',
        onTimePaymentPercentage: 'onTimePaymentPercentage',
        latePaymentPercentage: 'latePaymentPercentage',
        recentTradelinesOpened: 'recentTradelinesOpened',
        dateOfOldestTrade: 'dateOfOldestTrade',
        ageOfCredit: 'ageOfCredit',
        paymentHistory: 'paymentHistory',
        securityFreeze: 'securityFreeze',
        fraudAlert: 'fraudAlert',
      },
    },
  }